package exception;
public class Demo {
	public static void main(String[] args) {
		int a = 5;
      try {
    	System.out.println(a/0);}
     catch(ArithmeticException e){
    	System.err.println("error occured");}
    
    }}
    
	


